
-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 14:24:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geocode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geocode
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geocode` DEFAULT CHARACTER SET utf8 ;
USE `geocode` ;

-- -----------------------------------------------------
-- Table `geocode`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geocode`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `number_vehicles` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profil_image` VARCHAR(255) NULL,
  `role` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geocode`.`charging_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geocode`.`charging_station` (
  `id` INT NOT NULL,
  `operator` VARCHAR(45) NULL,
  `usage_type` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NULL,
  `adress` VARCHAR(255) NULL,
  `town` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `longitude` DECIMAL(65) NULL,
  `latitude` DECIMAL(65) NULL,
  `connectors_count` INT NULL,
  `connector_type` VARCHAR(45) NULL,
  `power` DECIMAL(65) NULL,
  `voltage` VARCHAR(45) NULL,
  `access_type` VARCHAR(45) NULL,
  `operating_hours` VARCHAR(45) NULL,
  `additional_info` TEXT(255) NULL,
  `date_created` DATE NULL,
  `source_url` VARCHAR(255) NULL,
  `coordinates` VARCHAR(45) NULL,
  `departement_code` VARCHAR(45) NULL,
  `departement_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geocode`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geocode`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geocode`.`plug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geocode`.`plug` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geocode`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geocode`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `informations` TEXT(1000) NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_model_brand1_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_model_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `geocode`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geocode`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geocode`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL,
  `vehicle_image` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `plug_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_vehicle_brand1_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_vehicle_plug1_idx` (`plug_id` ASC) VISIBLE,
  INDEX `fk_vehicle_model1_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `geocode`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `geocode`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_plug1`
    FOREIGN KEY (`plug_id`)
    REFERENCES `geocode`.`plug` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `geocode`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geocode`.`user_has_charging_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geocode`.`user_has_charging_station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `charging_station_id` INT NOT NULL,
  `reservation_date` DATE NOT NULL,
  `amount_paid` DECIMAL(65) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_charging_station_charging_station1_idx` (`charging_station_id` ASC) VISIBLE,
  INDEX `fk_user_has_charging_station_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_charging_station_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `geocode`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_charging_station_charging_station1`
    FOREIGN KEY (`charging_station_id`)
    REFERENCES `geocode`.`charging_station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
